### PR TITLE
coyarzun updates

### PR DESCRIPTION
**Pull request by montoyamoraga**
Resolves #[Add issue number here]

 Changes:

 Screenshots of the change:

#### PR Checklist

- [ ] `npm run lint` passes
- [ ] [Inline documentation] is included / updated
- [ ] [Unit tests] are included / updated

[Inline documentation]: https://github.com/processing/p5.js/blob/main/contributor_docs/inline_documentation.md
[Unit tests]: https://github.com/processing/p5.js/tree/main/contributor_docs#unit-tests

### CODE REVIEW

**Comment by harshsharma-11** [comment]
@montoyamoraga sir is this repo is currently accepting contributions as i think there is another sound repo??

**Comment by montoyamoraga** [comment]
@montoyamoraga yes!

**Comment by montoyamoraga** [comment]
@harshsharma-11 yes!

**Comment by harshsharma-11** [comment]
@montoyamoraga okk thanks for reply sir

**Pull request merged**
